refactor frontend

diff --git a/.github/workflows/docker_build_core.yaml b/.github/workflows/docker_build_core.yaml
--- a/.github/workflows/docker_build_core.yaml
+++ b/.github/workflows/docker_build_core.yaml
@@ -12,7 +12,46 @@ permissions:
   packages: write
 
 jobs:
-  build:
+  test:
+    name: pytest
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+      - name: test
+        working-directory: src/core
+        run: |
+          python -m pip install --upgrade -r ../../dev_requirements.txt
+          pip install -e .
+          echo "Starting Pytest"
+          pytest || echo "failed"
+          sqlite3 /var/tmp/taranis_test.db 'select * from user;'
+
+  build_wheel:
+    name: build wheel
+    runs-on: ubuntu-22.04
+    needs: test
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+      - name: build
+        working-directory: src/core
+        run: |
+          python -m pip install --upgrade pip setuptools wheel build
+          python -m build
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        if: startsWith(github.ref, 'refs/tags/')
+        with:
+          files: |
+            src/core/dist/taranis_ng_core-*.whl
+            src/core/dist/taranis_ng_core-*.tar.gz
+
+  build_docker:
     name: build docker
     runs-on: ubuntu-latest
     steps:
